"""change downvotes and upvotes model

Revision ID: 71bfebca1feb
Revises: 876651acb3f0
Create Date: 2021-04-26 17:54:06.812678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bfebca1feb'
down_revision = '876651acb3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('counter', sa.Integer(), nullable=True))
    op.add_column('upvotes', sa.Column('counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'counter')
    op.drop_column('downvotes', 'counter')
    # ### end Alembic commands ###
