"""update user model

Revision ID: fa5eaf30bfe7
Revises: 71bfebca1feb
Create Date: 2021-04-28 14:40:56.299782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5eaf30bfe7'
down_revision = '71bfebca1feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
